export const careerInterests = [
  "Accounting and Finance",
  "Actuarial Science",
  "Advertising",
  "Agriculture and Farming",
  "Architecture and Design",
  "Arts and Culture",
  "Automotive",
  "Banking",
  "Biotechnology",
  "Business and Management",
  "Chemical Engineering",
  "Civil Engineering",
  "Communications and Media",
  "Community Development",
  "Computer Science and IT",
  "Construction",
  "Consulting",
  "Counseling and Therapy",
  "Data Science and Analytics",
  "Dentistry",
  "Education and Teaching",
  "Electrical Engineering",
  "Energy and Utilities",
  "Entrepreneurship",
  "Environmental Science",
  "Fashion and Design",
  "Film and Television",
  "Financial Services",
  "Food and Beverage",
  "Forestry and Wildlife",
  "Gaming and Esports",
  "Government and Public Policy",
  "Healthcare and Medicine",
  "Hospitality and Tourism",
  "Human Resources",
  "Industrial Engineering",
  "Information Security",
  "Insurance",
  "Interior Design",
  "International Relations",
  "Investment Banking",
  "Journalism",
  "Law and Legal Services",
  "Logistics and Supply Chain",
  "Marketing",
  "Mechanical Engineering",
  "Medical Research",
  "Military and Defense",
  "Mining and Geology",
  "Non-Profit and NGOs",
  "Nursing",
  "Pharmaceuticals",
  "Photography",
  "Project Management",
  "Public Health",
  "Publishing and Editing",
  "Real Estate",
  "Renewable Energy",
  "Research and Development",
  "Retail",
  "Robotics",
  "Sales",
  "Science and Technology",
  "Social Work",
  "Software Development",
  "Sports and Fitness",
  "Telecommunications",
  "Transportation",
  "Urban Planning",
  "Veterinary Science",
  "Web Development",
  "Writing and Content Creation",
];
