export const coursesInKenyanUniversities = [
  "Accounting",
  "Actuarial Science",
  "Agricultural Economics",
  "Agricultural Engineering",
  "Agriculture",
  "Animal Science",
  "Anthropology",
  "Applied Statistics",
  "Architecture",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Biotechnology",
  "Botany",
  "Building and Construction Management",
  "Business Administration",
  "Business Information Technology",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Commerce",
  "Communication and Media Studies",
  "Community Development",
  "Computer Engineering",
  "Computer Science",
  "Construction Management",
  "Criminology",
  "Dentistry",
  "Development Studies",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Environmental Science",
  "Environmental Studies",
  "Finance",
  "Food Science and Technology",
  "Forestry",
  "Geography",
  "Geology",
  "Graphic Design",
  "Health Records and Information Management",
  "History",
  "Hospitality Management",
  "Human Resource Management",
  "Information Science",
  "Information Systems",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Law",
  "Library and Information Science",
  "Logistics and Supply Chain Management",
  "Marine Engineering",
  "Marketing",
  "Mass Communication",
  "Mathematics",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Medicine",
  "Microbiology",
  "Nursing",
  "Nutrition and Dietetics",
  "Occupational Therapy",
  "Pharmacy",
  "Physics",
  "Political Science",
  "Procurement and Supply Chain Management",
  "Project Management",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Quantity Surveying",
  "Real Estate",
  "Sociology",
  "Software Engineering",
  "Special Needs Education",
  "Sports Science",
  "Statistics",
  "Surveying",
  "Teaching",
  "Telecommunication Engineering",
  "Theology",
  "Tourism Management",
  "Veterinary Medicine",
  "Water Resources Engineering",
  "Wildlife Management",
  "Zoology",
];
