export const skills = [
  "Accounting",
  "Active Listening",
  "Adaptability",
  "Analytical Thinking",
  "Artificial Intelligence",
  "Attention to Detail",
  "Automation",
  "Biochemistry",
  "Biotechnology",
  "Budgeting",
  "Business Analysis",
  "Business Strategy",
  "C++",
  "CAD Design",
  "Cloud Computing",
  "Collaboration",
  "Communication",
  "Conflict Resolution",
  "Content Creation",
  "Copywriting",
  "Creative Thinking",
  "Critical Thinking",
  "Customer Service",
  "Cybersecurity",
  "Data Analysis",
  "Data Management",
  "Data Science",
  "Data Visualization",
  "Database Management",
  "Debugging",
  "Decision Making",
  "Deep Learning",
  "Digital Marketing",
  "Editing",
  "Electrical Engineering",
  "Electronics",
  "Empathy",
  "Entrepreneurship",
  "Environmental Science",
  "Event Planning",
  "Excel",
  "Financial Analysis",
  "Financial Management",
  "Front-end Development",
  "Fundraising",
  "Graphic Design",
  "HTML/CSS",
  "Human Resources",
  "Illustration",
  "Interpersonal Skills",
  "Interviewing",
  "iOS Development",
  "Java",
  "JavaScript",
  "Laboratory Skills",
  "Leadership",
  "Machine Learning",
  "Management",
  "Market Research",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medical Research",
  "Mobile Development",
  "Negotiation",
  "Networking",
  "Node.js",
  "Organizational Skills",
  "Patient Care",
  "Photography",
  "Photoshop",
  "PHP",
  "Planning",
  "Problem Solving",
  "Product Management",
  "Project Management",
  "Public Speaking",
  "Python",
  "Quality Assurance",
  "React",
  "Research",
  "Risk Management",
  "Sales",
  "Scientific Writing",
  "Search Engine Optimization (SEO)",
  "Social Media Management",
  "Software Development",
  "SQL",
  "Strategic Planning",
  "Stress Management",
  "Teaching",
  "Team Building",
  "Teamwork",
  "Technical Writing",
  "Time Management",
  "Translation",
  "Troubleshooting",
  "UI/UX Design",
  "Web Development",
  "WordPress",
  "Writing",
];
