export const universitiesInKenya = [
  "University of Nairobi",
  "Kenyatta University",
  "Moi University",
  "Jomo Kenyatta University of Agriculture and Technology",
  "Egerton University",
  "Maseno University",
  "Technical University of Kenya",
  "Masinde Muliro University of Science and Technology",
  "Chuka University",
  "Meru University of Science and Technology",
  "Kisii University",
  "Murang'a University of Technology",
  "South Eastern Kenya University",
  "Maasai Mara University",
  "Dedan Kimathi University of Technology",
  "Pwani University",
  "Karatina University",
  "University of Eldoret",
  "Laikipia University",
  "Kirinyaga University",
  "University of Kabianga",
  "Machakos University",
  "The Co-operative University of Kenya",
  "Taita Taveta University",
  "Garissa University",
  "Rongo University",
  "Embu University",
  "University of Embu",
  "Kenya Methodist University",
  "Mount Kenya University",
  "Strathmore University",
  "Daystar University",
  "United States International University (USIU)",
  "Africa Nazarene University",
  "Catholic University of Eastern Africa",
  "KCA University",
  "St. Paul's University",
  "Pan Africa Christian University",
  "Kenya Highlands Evangelical University",
  "Gretsa University",
  "Zetech University",
  "Riara University",
  "Adventist University of Africa",
  "Great Lakes University of Kisumu",
  "International Leadership University",
  "KAG East University",
  "Kenya Aeronautical College",
  "Kiriri Women's University of Science and Technology",
  "Lukenya University",
  "Marist International University College",
  "Pioneer International University",
  "Regent International University College",
  "Scott Christian University",
  "UMMA University",
  "Uzima University College",
];
